### ISSUE TITLE
Add Barnette Graphs

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#25]
See:
http://mathworld.wolfram.com/Barnette-Bosak-LederbergGraph.html

Add names and doctests.

**Comment by nvcleemp** [comment]
Note that it is just one graph and two images of the same graph are given on that page. It can be constructed by talking two Tutte fragments and adding some connections between it (Grünbaum's embedding shows this best).

This is a plane graph, so it would be best to also include the embedding, but since it is a 3-connected graph this embedding is implied.

**Comment by rbarden** [comment]
I found it's g6 string confirmed by House of Graphs database.
