### ISSUE TITLE
Add STSP integrality gap examples

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#433]
n=6,7,8,9,10 graphs (with weights)on p.927 of Benoit-Boyd (2008):
[benoit-boyd-integrality-gap-small-TSPs-2008.pdf](https://github.com/math1um/objects-invariants-properties/files/1984865/benoit-boyd-integrality-gap-small-TSPs-2008.pdf)

coding the generator at the bottom of p.927 would be really great.

**Comment by thenealon** [comment]
Generator with weights:

```
def benoit_boyd_graphs(a,b,c):
    g=Graph(0,weighted=true)
    for i in [1..a]:
        g.add_edge(i,i+1,1)
    for i in [a+2..a+b+1]:
        g.add_edge(i,i+1,1)
    for i in [a+b+3..a+b+c+2]:
        g.add_edge(i,i+1,1)
    g.add_edges([(1,a+2,0.5),(a+2,a+b+3,0.5),(1,a+b+3,0.5),(a+1,a+b+2,0.5),(a+1,a+b+c+3,0.5),(a+b+2,a+b+c+3,0.5)])
    g.relabel()
    return g
```

**Comment by yirkajk** [comment]
I added the factory @thenealon provided from p.927, and the factory with more complicated weights from p.928.
I didn't add the specific graphs for n=6...10 since graph 6 strings don't encode weighting, so there's no really good way to save them. It should be easy enough to build them using the code from the generators, if anybody wants them.
