### ISSUE TITLE
Add property: weakly pancyclic

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#435]
This property should be in gt.sage.

Its defined:
https://www.sciencedirect.com/science/article/pii/S0095895699919160

**Comment by raynorj** [comment]
def is_weakly_pancyclic(g):
    #Theorem 22 in Gould (2002), Advances on the Hamiltonian Problem
    #get number of vertices (order), n
    n = len(g.vertices())
    #get number of edges (size), q
    q = len(g.edges())

    if q > floor(math.pow(n-1, 2)/4+1) and not g.is_bipartite():
        return True
    else:
        return False

**Comment by raynorj** [comment]
`def is_weakly_pancyclic(g):
    cycle_lengths = []

    #enumerate cycles in graph via depth-first search
    for vertex in g.vertices():
        path_stack = [[vertex]]

        while len(path_stack) > 0:
            path = path_stack.pop()

            for v in g[path[-1]]:
                if v not in path:
                    path_stack.append(path[:]+[v])
                else:
                    if (v == path[0]) and (len(path) > 2):
                        #cycle encountered, save cycle length
                        cycle_lengths.append(len(path))
                    #implicitly, we cease searching along this path, as we don't push to the stack

    #if no cycles exist, return false
    if len(cycle_lengths) > 0:
        #if any gaps exist, return false
        cycle_lengths.sort()
        for i in range(1, len(cycle_lengths)):
            pred_length = cycle_lengths[i-1]
            curr_length = cycle_lengths[i]
            if (curr_length != pred_length) and ((curr_length-1) != pred_length):
                return False
    else:
        return False

    #otherwise, return true
    return True`

**Comment by yirkajk** [comment]
Jesse, after our conversation, I think your current idea is better than mine.

If you'd like to check it out, the idea was to iterate over cycle graphs using graphs.subgraph_search() or graphs.subgraph_search_count(). These then call [SubgraphSearch](https://github.com/sagemath/sagelib/blob/master/sage/graphs/generic_graph_pyx.pyx). It looks like this would scale as O(n^3). And, it's written to return **all** corresponding subgraphs, which for C_n would return at least n graphs. We'd want to rewrite it to skip this since we only need a boolean.

I think your current implementation also scales as O(n^3).  The reason I like it more is that we can improve on it more easily. 
I'm interested in how to improve the runtime, either asymptotically or practically, using dynamic programming. You can imagine, for example, if I just gave you a cycle graph, your current algorithm checks from vertex 1 to 2 to ... to 5, and then checks 1 to 5 to 4 to ... 1. It would be nice to avoid repetition.

Anyways, I can verify your current implementation and merge it tomorrow.
If you'd like to get fancy and use dynamic programming, or even use some randomization to enforce average-case complexity, then that would be a cool enhancement.

**Comment by math1um** [comment]
Please add doctests: K5 is, petersen is not.

What's an example of a graph that's weakly pancyclic but not pancyclic?

Add a note about how the function handles trees.

**Comment by yirkajk** [comment]
We're not sure about your definition for is_pancyclic.
Pancyclic requires all cycles from 3 to n. Weakly pancyclic is cycles from the girth to the circumference.
So, weakly pancyclic AND hamiltonian definitely gives us cycles from girth to n... but what if the girth is greater than 3?

**Comment by yirkajk** [comment]
I split @raynorj's code up into several methods, including a utility `cycle_lengths`, which I then use as the basis for `is_pancyclic` and `is_weakly_pancyclic`.
Also, it made for an easy `circumfrence()` method!

One last thing:
I defined that if g is acyclic, then `is_weakly_pancyclic` returns False. @thenealon, do you have a different opinion? We can return True, False, or throw an error.

**Comment by thenealon** [comment]
I do think that if G is acyclic, then `is_weakly_pancyclic` should return False -- the girth is +Infinity, and the circumference is 0.  Since there are no cycle lengths greater than +Infinity and smaller than 0, there is nothing to check and the graph is vacuously weakly pancyclic.

(this is based on the definition of weakly pancyclic from [Bollobas/Thomason '99](https://www.sciencedirect.com/science/article/pii/S0095895699919160) )

**Comment by yirkajk** [comment]
Is circumference = 0 a standard definition?
@math1um had a strange reaction when I read this to him. And Mathematica just refuses to give a result for acyclic graphs.
If it's standard, we should return True. But, if it's uncertain, then I can set `weakly_pancyclic` and `circumference` to throw errors on acyclic graphs.

**Comment by math1um** [comment]
I think GT should probably throw an error here. 

The girth and circumference of acyclic graphs don't follow the main ideas of these terms and are thus *purely* definitional.

Nico, is it better for Conjecturing to have non-values in its calculation table, or defined values (like "0" or "Infty")?

**Comment by nvcleemp** [comment]
That's philosophical question. Values like 0 and Infty will be used. Non-values will be ignored. So if you define the circumference of a graph as infinity for acyclic graph, you are running upper bounds for the circumference, and you have an acylic graph in your objects list, then you won't get any conjectures.

My guess would be that non-values are the best choice. Graphs which have such degenerate values for an invariant are usually not interesting to consider in conjectures about that invariant.

**Comment by thenealon** [comment]
I'm not sure it matters, but I disagree with this throwing an error. `is_weakly_pancylic` is a simple property -- does the graph have cycles of the right lengths?  This is a yes/no answer, so I don't understand why the answer for a tree would be `Error: OH NO A TREE!`.  

Defining the circumference to be infinite for acyclic graphs would cause problems, you're right -- but it should be the maximum of an empty set of natural numbers, which is 0 (and which won't cause issues hunting for upper bounds on circumference).

I'll leave this alone now; I'm not really bothered by either choice, but thought I'd give my two cents.

**Comment by math1um** [comment]
> the maximum of an empty set of natural numbers, which is 0

That is, max({})=0 iff 0 >= x, for every x in {}. 

Is the RHS of this equivalence true? (And, if so, is it also true that max({})=1?)

**Comment by yirkajk** [comment]
I set them both to throw errors.
I've grown to think of errors more as "IDK" than always "OH NO". Although the latter would be more entertaining.
Basically, I / we don't know what to do with this, but if a user prefers a certain thing, it's hopefully simple to just catch the error and substitute 0.
