### ISSUE TITLE
Add utility: extend a graph until maximal edges and triangle-free

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#496]
this function can be useful is investigating questions about triangle-free graphs.

doctest comments:

-this takes a graph and adds edges without creating triangles. the output is not the only possible edge-maximal triangle-free extension.
-add edges until it is not possible to add an edge without creating a triangle
-if graph is NOT triangle-free it just returns that graph
```
def extremal_triangle_free_extension(g):
    if not g.is_triangle_free():
        return g
    E = g.edges(labels=false)
    V = g.vertices()
    n = g.order()
    gcopy = copy(g)
    for i in range(n):
        for j in range(n):
            if j>i and (V[i],V[j]) not in E and (V[j],V[i]) not in E:               
                gcopy.add_edge(V[i],V[j])
                if not gcopy.is_triangle_free():
                    gcopy.delete_edge(V[i],V[j])
    return gcopy 
```

**Comment by nvcleemp** [comment]
I don't like the fact that it just returns g if g is not triangle-free. A more logical choice would be to throw an error. That way the output will always be a triangle-free graph.

Instead of adding an edge, checking whether the resulting the graph is triangle-free, and if not, removing the edge, it might be more efficient to only add the edge if the neighbourhoods of the vertices have an empty intersection.

**Comment by math1um** [comment]
Maybe it should return k1 if not triangle-free?

If you strip of edges you may get that anyway (e.g. for stars). if you always return k1 and put a note in the doctest, at least you can easily throw those away?

**Comment by math1um** [comment]
OK, that makes sense.
