### ISSUE TITLE
Several doctests fail

### ISSUE THREAD

**Issue by nvcleemp** [math1um/objects-invariants-properties#530]
Currently we have about 37 failures when running the doctests. Many are due to errors in the tests.

**Comment by yirkajk** [comment]
gt.sage passes all doctests!
The only remaining problem is the memory error caused by `janko_kharaghani1800`. Right now, we need to comment out that graph before running tests. If that graph is present, it causes a RunTime error.

@nvcleemp What would you like to do with `janko_kharaghani1800`? Should we open it as a separate issue?

**Comment by yirkajk** [comment]
Opened Issue #541 to handle janko_kharaghani1800. 
Commented out the graph until it's fixed. So, the current version of gt.sage passes all tests as-is, closing this issue.
