### ISSUE TITLE
Add invariant for number of "large degree" vertices

### ISSUE THREAD

**Issue by math1um** [math1um/objects-invariants-properties#655]
Namely, number of vertices of degree >= floor(n/2); maybe these need a memorable name? 

These show up in thinking about graphs where the independence number (alpha) equals 2. These graphs are dense and have a lot of these "large degree" vertices.

**Comment by math1um** [comment]
Added invariant to invariants.sage

**Comment by thenealon** [comment]
Too late; but maybe it makes sense to call these ‘Dirac vertices’?  (Since their most common use is in Dirac’s Thm for hamiltonicity, https://en.wikipedia.org/wiki/Dirac%27s_theorem)

/////////////////////////
Neal Bushaw
Dept. of Math. & Appl. Mathematics
SYSM PhD Faculty
Virginia Commonwealth University

**Comment by math1um** [comment]
Changed name to dirac_number
